In [6]:
# 410921208_楊右宇
# Python 3.9.7

import pandas as pd
import numpy as np

df = pd.read_csv(
    r'D:\OneDrive - 國立東華大學\code\5_School_Work\S4\Datascience\week_5\data.csv')


res = pd.DataFrame(0, index=range(0, 6), columns=['High school system', 'Gender', 'Num of graduates', 'enroll in police university', 'enroll in police college',
                   'average enroll in military', 'Police university enrollment rate', 'Police college enrollment rate', 'Military school enrollment rate'])

res.iloc[:, 0] = ['National', 'National', 'county & city',
                  'county & city', 'private', 'private']
res.iloc[:, 1] = ['male', 'female', 'male', 'female', 'male', 'female']

for i in range(6):

    target = df[(df.loc[:, 'High school system'] == res.loc[res.index[i], 'High school system']) &
                (df.loc[:, 'Gender'] == res.loc[res.index[i], 'Gender'])]

#     print(target)
    target.to_csv(str(i) + '.csv')
    res.loc[res.index[i], 'Num of graduates'] = \
        target.loc[:, 'Num of graduates'].sum()

    res.loc[res.index[i], 'enroll in police university'] = \
        target.loc[:, 'Num of enroll in police university'].sum()
    res.loc[res.index[i], 'enroll in police college'] = \
        target.loc[:, 'Num of enroll in police college'].sum()

    res.loc[res.index[i], 'average enroll in military'] = \
        round(target.loc[:, 'Num of enroll in military school'].mean(), 2)

    res.loc[res.index[i], 'Police university enrollment rate'] = \
        '{:.2f}'.format(round(res.loc[res.index[i], 'enroll in police university'] /
                              res.loc[res.index[i], 'Num of graduates'], 4) * 100) + '%'
    res.loc[res.index[i], 'Police college enrollment rate'] = \
        '{:.2f}'.format(round(res.loc[res.index[i], 'enroll in police college'] /
                              res.loc[res.index[i], 'Num of graduates'], 4) * 100) + '%'
    res.loc[res.index[i], 'Military school enrollment rate'] = \
        '{:.2f}'.format(round(target.loc[:, 'Num of enroll in military school'].sum() /
                              res.loc[res.index[i], 'Num of graduates'], 4) * 100) + '%'


print(res)
res.to_csv('result.csv')

  High school system  Gender  Num of graduates  enroll in police university  \
0           National    male             45412                           66
1           National  female             41984                           14
2      county & city    male             35960                           27
3      county & city  female             33110                           11
4            private    male             44471                           10
5            private  female             40351                            7

   enroll in police college  average enroll in military  \
0                       567                      134.17
1                        58                       65.33
2                       300                       70.60
3                        38                       31.80
4                        29                      116.75
5                        16                       36.25

  Police university enrollment rate Police college enrollment rate  \
0                             0.15%                          1.25%
1                             0.03%                          0.14%
2                             0.08%                          0.83%
3                             0.03%                          0.11%
4                             0.02%                          0.07%
5                             0.02%                          0.04%

  Military school enrollment rate
0                           1.77%
1                           0.93%
2                           0.98%
3                           0.48%
4                           1.05%
5                           0.36%

In [3]:
from tkinter.tix import DisplayStyle
import pandas as pd

data1 = r'D:\OneDrive - 國立東華大學\code\5_School_Work\S4\Datascience\week_5\data.csv'
df = pd.read_csv(data1)
# print(df)

c_df2 = df.groupby(['High school system', 'Gender']).agg(
    Num_of_graduates=pd.NamedAgg(column="Num of graduates", aggfunc="sum"),
    Num_of_enroll_in_police_university=pd.NamedAgg(
        column="Num of enroll in police university", aggfunc="sum"),
    Num_of_enroll_in_police_college=pd.NamedAgg(
        column="Num of enroll in police college", aggfunc="sum"),
    Num_of_enroll_in_military_school=pd.NamedAgg(
        column="Num of enroll in military school", aggfunc="sum"),
    count=pd.NamedAgg(column="High school system", aggfunc="count")).reset_index()

c_df2['Military school enrollment average'] = c_df2['Num_of_enroll_in_military_school']/c_df2['count']
c_df2['police university enrollment rate'] = c_df2['Num_of_enroll_in_police_university'] / \
    c_df2['Num_of_graduates']
c_df2['Police college enrollment rate'] = c_df2['Num_of_enroll_in_police_college'] / \
    c_df2['Num_of_graduates']
c_df2['Military school enrollment rate'] = c_df2['Num_of_enroll_in_military_school'] / \
    c_df2['Num_of_graduates']

c_df2 = c_df2.drop(['count', 'Num_of_enroll_in_military_school'], axis=1)
print(c_df2)

  High school system  Gender  Num_of_graduates  \
0           National  female             41984
1           National    male             45412
2      county & city  female             33110
3      county & city    male             35960
4            private  female             40351
5            private    male             44471

   Num_of_enroll_in_police_university  Num_of_enroll_in_police_college  \
0                                  14                               58
1                                  66                              567
2                                  11                               38
3                                  27                              300
4                                   7                               16
5                                  10                               29

   Military school enrollment average  police university enrollment rate  \
0                           65.333333                           0.000333
1                          134.166667                           0.001453
2                           31.800000                           0.000332
3                           70.600000                           0.000751
4                           36.250000                           0.000173
5                          116.750000                           0.000225

   Police college enrollment rate  Military school enrollment rate
0                        0.001381                         0.009337
1                        0.012486                         0.017727
2                        0.001148                         0.004802
3                        0.008343                         0.009816
4                        0.000397                         0.003593
5                        0.000652                         0.010501